name: smartblooddonor
description: Smart Blood Donation

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fluttertoast: ^4.0.0
  sliding_up_panel: ^1.0.2
  rxdart: ^0.24.0
  flutter_redux: ^0.6.0
  redux_thunk: ^0.3.0

  geolocator: any

  firebase_core: any
  firebase_auth: any
  firebase_analytics: any
  cloud_firestore: any

  google_sign_in: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/flags/in.png
    - assets/images/google_logo.png

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
          style: normal
        - asset: fonts/Roboto-Italic.ttf
          style: italic
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Roboto-Light.ttf
          weight: 100
    - family: Roboto Mono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
          style: normal
        - asset: fonts/RobotoMono-Italic.ttf
          style: italic
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700
        - asset: fonts/RobotoMono-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/RobotoMono-Light.ttf
          weight: 100
